version: "3"
services:
  postgres:
    image: postgres:12
    environment:
    - POSTGRES_DB=qrytest
    - POSTGRES_USER=qry
    - POSTGRES_PASSWORD=password
    ports:
    - 54321:5432
  mysql:
    image: mysql:8
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=qrytest
    - MYSQL_USER=qry
    - MYSQL_PASSWORD=password
    ports:
    - 33060:3306
