#!/usr/bin/env python

from glob import glob
from os import path
from shutil import copy

for init_path in glob('**/__init__.py', recursive = True):
	interface_path = init_path.replace('.py', '.pyi')
	if path.getsize(init_path) == 0:
		continue

	copy(init_path, interface_path)
